workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    scripts:
      - name: Make gradlew executable
        script: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            echo "gradlew executable set"
          else
            echo "gradlew not found, skipping"
          fi
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk


